### ISSUE TITLE
Missing closing curly brace in Stash

### ISSUE THREAD

**Issue by achyuta116** [nkilm/learning-git#1]
[Stash - reapplying changes ](https://github.com/nkilm/learning-git#stash) missing brace on the last line
<img width="879" alt="Screenshot 2022-07-24 at 8 25 50 PM" src="https://user-images.githubusercontent.com/65274782/180652871-2ad1442d-51fa-4b8c-bf77-062aab1bba84.png">

**Comment by nkilm** [comment]
Thank you for the `correction`!
